name: weld_research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pythonocc-core
  - numpy=1.24.3
  - pip
  - pip:
    - flask==3.0.0
    - flask-cors==4.0.0
    - werkzeug==3.0.1